### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Applications/node_modules/macos-focus-mode/bin/cli.js

### ISSUE THREAD

**Issue by Suplanus** [arodik/macos-focus-mode#2]
Would love to use it but I not know about Node.js.

I installed it via `npm i macos-focus-mode` to a local folder.
When I execute `macos-focus-mode install` the shell dont know the command.
So I navigated to the Bin folder and tried: `node cli.js`. But getting this error:
```
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Applications/node_modules/macos-focus-mode/bin/cli.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

NPM: `v12.16.2`

**Comment by arodik** [comment]
Install it globally if you want to use it from the CLI

```
npm i -g macos-focus-mode

macos-focus-mode install
macos-focus-mode enable
```

If you want to use it as a package
- install it locally (`npm i macos-focus-mode`) 
- put   "type": "module" into your package-json

**Comment by Suplanus** [comment]
🙈
Great. Thank you. Perhaps you take it into readme for noobs like me 💖
